# Generated by Django 3.1.4 on 2020-12-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.CharField(max_length=100)),
                ('apt_number', models.CharField(blank=True, max_length=100, verbose_name='Apt/Unit Number:')),
                ('phone_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('church', models.CharField(max_length=10)),
                ('iwaspathfinder', models.BooleanField(default=False, verbose_name='I have been a Pathfinder')),
                ('ifyespathfinder', models.CharField(max_length=100, verbose_name='at')),
                ('dadismasterguide', models.BooleanField(default=False, verbose_name='My dad is a Master Guide')),
                ('dadwaspathfinder', models.BooleanField(default=False, verbose_name='My father has been a Pathfinder')),
                ('momismasterguide', models.BooleanField(default=False, verbose_name='My mother is a Master Guide')),
                ('momwaspathfinder', models.BooleanField(default=False, verbose_name='My mother has been a Pathfinder')),
                ('wishspecialclub', models.CharField(max_length=100, verbose_name='I wish to join the following Special Club Program')),
            ],
        ),
    ]
